name: Specific version build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build"
        required: true

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          lfs: true

      - name: Build
        id: build
        shell: cmd
        run: call windows_build.cmd
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}-windows
          path: github
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          lfs: true

      - name: Build
        id: build
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}
        run: |
          chmod +x ./linux_build.sh
          ./linux_build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}-linux
          path: github
          if-no-files-found: error

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          lfs: true

      - name: Build
        id: build
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}
        run: |
          chmod +x ./macos_build.sh
          ./macos_build.sh

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}-macos
          path: github
          if-no-files-found: error